name: test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  BUILD_TYPE: Debug

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build (gcc)
        run: >
          cmake -B ${{github.workspace}}/build 
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DCMAKE_CXX_COMPILER=g++ 
          -DCMAKE_C_COMPILER=gcc 
          -DDR_TEST=ON && 
          cmake --build ${{github.workspace}}/build

      - name: Build (clang)
        run: >
          cmake -B ${{github.workspace}}/build 
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DCMAKE_CXX_COMPILER=clang++ 
          -DCMAKE_C_COMPILER=clang 
          -DDR_TEST=ON && 
          cmake --build ${{github.workspace}}/build

      - name: Test
        run: ${{github.workspace}}/build/test/dr-test

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: >
          choco install ninja

      - name: Build (clang)
        run: >
          cmake -B ${{github.workspace}}/build -G "Ninja" 
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DCMAKE_CXX_COMPILER=clang++ 
          -DCMAKE_C_COMPILER=clang 
          -DDR_TEST=ON && 
          cmake --build ${{github.workspace}}/build

      - name: Test
        run: ${{github.workspace}}/build/test/dr-test.exe
